language: php
dist: bionic

sudo: required

services:
  - mysql

addons:
  firefox: "47.0.1"
  postgresql: "9.6"
  chrome: stable
  apt:
    packages:
      - openjdk-8-jre-headless
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.3

env:
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=master

matrix:
  include:
    # Only Moodle 37 and onwards has php 7.3 support
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=pgsql
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_38_STABLE DB=pgsql
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://127.0.0.1 &

install:
  - moodle-plugin-ci install

script:
  - /home/travis/build/moodle/vendor/bin/phpunit "provider_testcase" /home/travis/build/moodle/privacy/tests/provider_test.php
  - /home/travis/build/moodle/vendor/bin/phpunit "tool_dataprivacy_expired_contexts_testcase" /home/travis/build/moodle/admin/tool/dataprivacy/tests/expired_contexts_test.php
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache || true
  - moodle-plugin-ci grunt || [ "$MOODLE_BRANCH" = 'master' ] || [ "$MOODLE_BRANCH" = 'MOODLE_38_STABLE' ]
  - moodle-plugin-ci phpdoc || true # Report errors but don't fail the build (until they are fixed)
  - moodle-plugin-ci phpunit --coverage-text
  #- moodle-plugin-ci behat --profile chrome # chromium is mostly broken
  - moodle-plugin-ci behat # with Firefox, which mostly works
